[23/Mar/2020 14:07:29] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 14:07:30] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 14:07:47] DEBUG [django.template:872] Exception while resolving variable 'name' in template 'Diabetes/Report.html'.
Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x000002D894FB1598>>, 'request': <WSGIRequest: POST '/diabriskpred/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x000002D8A630E400>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x000002D8A7482C18>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x000002D8A7413F98>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'cholesterol': '15.3', 'hemoglobin': '34.2'}, {'block': <Block Node: content. Contents: [<TextNode: '\n<!DOCTYPE html>\n<html la'>, <django.templatetags.static.StaticNode object at 0x000002D8A74858D0>, <TextNode: '" rel="stylesheet" />\n   '>, <Variable Node: name>, <TextNode: '\n                        '>, <Variable Node: age>, <TextNode: '\n                        '>, <Variable Node: gender>, <TextNode: '\n                        '>, <Variable Node: height>, <TextNode: '\n                        '>, <Variable Node: weight>, <TextNode: '\n                        '>, <Variable Node: hemoglobin>, <TextNode: '\n                        '>, <TextNode: '\n        <div class="prog'>, <TextNode: '\n                        '>, <TextNode: '\n                        '>, <Variable Node: bmi_calc>, <TextNode: '\n                        '>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n\n                       '>, <TextNode: '\n                        '>, <Variable Node: cholesterol>, <TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x000002D8A7482E48>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x000002D8A7482DD8>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x000002D8A7482D30>, <TextNode: '" type="text/javascript">'>]>}]
[23/Mar/2020 14:07:47] DEBUG [django.template:872] Exception while resolving variable 'age' in template 'Diabetes/Report.html'.
Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'age'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'age'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'age'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [age] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x000002D894FB1598>>, 'request': <WSGIRequest: POST '/diabriskpred/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x000002D8A630E400>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x000002D8A7482C18>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x000002D8A7413F98>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'cholesterol': '15.3', 'hemoglobin': '34.2'}, {'block': <Block Node: content. Contents: [<TextNode: '\n<!DOCTYPE html>\n<html la'>, <django.templatetags.static.StaticNode object at 0x000002D8A74858D0>, <TextNode: '" rel="stylesheet" />\n   '>, <Variable Node: name>, <TextNode: '\n                        '>, <Variable Node: age>, <TextNode: '\n                        '>, <Variable Node: gender>, <TextNode: '\n                        '>, <Variable Node: height>, <TextNode: '\n                        '>, <Variable Node: weight>, <TextNode: '\n                        '>, <Variable Node: hemoglobin>, <TextNode: '\n                        '>, <TextNode: '\n        <div class="prog'>, <TextNode: '\n                        '>, <TextNode: '\n                        '>, <Variable Node: bmi_calc>, <TextNode: '\n                        '>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n\n                       '>, <TextNode: '\n                        '>, <Variable Node: cholesterol>, <TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x000002D8A7482E48>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x000002D8A7482DD8>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x000002D8A7482D30>, <TextNode: '" type="text/javascript">'>]>}]
[23/Mar/2020 14:07:47] DEBUG [django.template:872] Exception while resolving variable 'gender' in template 'Diabetes/Report.html'.
Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'gender'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'gender'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'gender'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [gender] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x000002D894FB1598>>, 'request': <WSGIRequest: POST '/diabriskpred/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x000002D8A630E400>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x000002D8A7482C18>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x000002D8A7413F98>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'cholesterol': '15.3', 'hemoglobin': '34.2'}, {'block': <Block Node: content. Contents: [<TextNode: '\n<!DOCTYPE html>\n<html la'>, <django.templatetags.static.StaticNode object at 0x000002D8A74858D0>, <TextNode: '" rel="stylesheet" />\n   '>, <Variable Node: name>, <TextNode: '\n                        '>, <Variable Node: age>, <TextNode: '\n                        '>, <Variable Node: gender>, <TextNode: '\n                        '>, <Variable Node: height>, <TextNode: '\n                        '>, <Variable Node: weight>, <TextNode: '\n                        '>, <Variable Node: hemoglobin>, <TextNode: '\n                        '>, <TextNode: '\n        <div class="prog'>, <TextNode: '\n                        '>, <TextNode: '\n                        '>, <Variable Node: bmi_calc>, <TextNode: '\n                        '>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n\n                       '>, <TextNode: '\n                        '>, <Variable Node: cholesterol>, <TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x000002D8A7482E48>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x000002D8A7482DD8>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x000002D8A7482D30>, <TextNode: '" type="text/javascript">'>]>}]
[23/Mar/2020 14:07:47] DEBUG [django.template:872] Exception while resolving variable 'height' in template 'Diabetes/Report.html'.
Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'height'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'height'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'height'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [height] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x000002D894FB1598>>, 'request': <WSGIRequest: POST '/diabriskpred/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x000002D8A630E400>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x000002D8A7482C18>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x000002D8A7413F98>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'cholesterol': '15.3', 'hemoglobin': '34.2'}, {'block': <Block Node: content. Contents: [<TextNode: '\n<!DOCTYPE html>\n<html la'>, <django.templatetags.static.StaticNode object at 0x000002D8A74858D0>, <TextNode: '" rel="stylesheet" />\n   '>, <Variable Node: name>, <TextNode: '\n                        '>, <Variable Node: age>, <TextNode: '\n                        '>, <Variable Node: gender>, <TextNode: '\n                        '>, <Variable Node: height>, <TextNode: '\n                        '>, <Variable Node: weight>, <TextNode: '\n                        '>, <Variable Node: hemoglobin>, <TextNode: '\n                        '>, <TextNode: '\n        <div class="prog'>, <TextNode: '\n                        '>, <TextNode: '\n                        '>, <Variable Node: bmi_calc>, <TextNode: '\n                        '>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n\n                       '>, <TextNode: '\n                        '>, <Variable Node: cholesterol>, <TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x000002D8A7482E48>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x000002D8A7482DD8>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x000002D8A7482D30>, <TextNode: '" type="text/javascript">'>]>}]
[23/Mar/2020 14:07:47] DEBUG [django.template:872] Exception while resolving variable 'weight' in template 'Diabetes/Report.html'.
Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'weight'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'weight'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'weight'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [weight] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x000002D894FB1598>>, 'request': <WSGIRequest: POST '/diabriskpred/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x000002D8A630E400>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x000002D8A7482C18>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x000002D8A7413F98>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'cholesterol': '15.3', 'hemoglobin': '34.2'}, {'block': <Block Node: content. Contents: [<TextNode: '\n<!DOCTYPE html>\n<html la'>, <django.templatetags.static.StaticNode object at 0x000002D8A74858D0>, <TextNode: '" rel="stylesheet" />\n   '>, <Variable Node: name>, <TextNode: '\n                        '>, <Variable Node: age>, <TextNode: '\n                        '>, <Variable Node: gender>, <TextNode: '\n                        '>, <Variable Node: height>, <TextNode: '\n                        '>, <Variable Node: weight>, <TextNode: '\n                        '>, <Variable Node: hemoglobin>, <TextNode: '\n                        '>, <TextNode: '\n        <div class="prog'>, <TextNode: '\n                        '>, <TextNode: '\n                        '>, <Variable Node: bmi_calc>, <TextNode: '\n                        '>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n\n                       '>, <TextNode: '\n                        '>, <Variable Node: cholesterol>, <TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x000002D8A7482E48>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x000002D8A7482DD8>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x000002D8A7482D30>, <TextNode: '" type="text/javascript">'>]>}]
[23/Mar/2020 14:07:47] DEBUG [django.template:872] Exception while resolving variable 'bmi_calc' in template 'Diabetes/Report.html'.
Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'bmi_calc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'bmi_calc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'bmi_calc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [bmi_calc] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x000002D894FB1598>>, 'request': <WSGIRequest: POST '/diabriskpred/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x000002D8A630E400>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x000002D8A7482C18>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x000002D8A7413F98>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'cholesterol': '15.3', 'hemoglobin': '34.2'}, {'block': <Block Node: content. Contents: [<TextNode: '\n<!DOCTYPE html>\n<html la'>, <django.templatetags.static.StaticNode object at 0x000002D8A74858D0>, <TextNode: '" rel="stylesheet" />\n   '>, <Variable Node: name>, <TextNode: '\n                        '>, <Variable Node: age>, <TextNode: '\n                        '>, <Variable Node: gender>, <TextNode: '\n                        '>, <Variable Node: height>, <TextNode: '\n                        '>, <Variable Node: weight>, <TextNode: '\n                        '>, <Variable Node: hemoglobin>, <TextNode: '\n                        '>, <TextNode: '\n        <div class="prog'>, <TextNode: '\n                        '>, <TextNode: '\n                        '>, <Variable Node: bmi_calc>, <TextNode: '\n                        '>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n\n                       '>, <TextNode: '\n                        '>, <Variable Node: cholesterol>, <TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x000002D8A7482E48>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x000002D8A7482DD8>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x000002D8A7482D30>, <TextNode: '" type="text/javascript">'>]>}]
[23/Mar/2020 14:07:47] INFO [django.server:154] "POST /diabriskpred/ HTTP/1.1" 200 27125
[23/Mar/2020 14:07:48] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 15:46:03] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 15:56:54] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 15:56:58] INFO [django.server:154] "GET / HTTP/1.1" 200 11446
[23/Mar/2020 15:56:58] INFO [django.server:154] "GET / HTTP/1.1" 200 11446
[23/Mar/2020 15:57:47] WARNING [django.request:228] Not Found: /static/js/popper.min.js.map
[23/Mar/2020 15:57:47] WARNING [django.request:228] Not Found: /static/js/bootstrap.min.js.map
[23/Mar/2020 15:57:47] WARNING [django.server:154] "GET /static/js/popper.min.js.map HTTP/1.1" 404 77
[23/Mar/2020 15:57:47] WARNING [django.server:154] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 77
[23/Mar/2020 15:58:08] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 15:58:09] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 15:58:12] WARNING [django.request:228] Not Found: /static/js/popper.min.js.map
[23/Mar/2020 15:58:12] WARNING [django.request:228] Not Found: /static/js/bootstrap.min.js.map
[23/Mar/2020 15:58:12] WARNING [django.server:154] "GET /static/js/popper.min.js.map HTTP/1.1" 404 77
[23/Mar/2020 15:58:12] WARNING [django.server:154] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 77
[23/Mar/2020 15:58:51] WARNING [django.request:228] Not Found: /static/scss/_reboot.scss
[23/Mar/2020 15:58:51] WARNING [django.server:154] "GET /static/scss/_reboot.scss HTTP/1.1" 404 77
[23/Mar/2020 16:03:03] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 16:03:04] WARNING [django.request:228] Not Found: /static/scss/_reboot.scss
[23/Mar/2020 16:03:04] WARNING [django.server:154] "GET /static/scss/_reboot.scss HTTP/1.1" 404 77
[23/Mar/2020 16:03:04] WARNING [django.request:228] Not Found: /static/js/popper.min.js.map
[23/Mar/2020 16:03:04] WARNING [django.request:228] Not Found: /static/js/bootstrap.min.js.map
[23/Mar/2020 16:03:04] WARNING [django.server:154] "GET /static/js/popper.min.js.map HTTP/1.1" 404 77
[23/Mar/2020 16:03:04] WARNING [django.server:154] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 77
[23/Mar/2020 16:03:04] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 16:05:10] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 16:05:11] WARNING [django.request:228] Not Found: /static/scss/_reboot.scss
[23/Mar/2020 16:05:11] WARNING [django.server:154] "GET /static/scss/_reboot.scss HTTP/1.1" 404 77
[23/Mar/2020 16:05:11] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 16:05:11] WARNING [django.request:228] Not Found: /static/js/bootstrap.min.js.map
[23/Mar/2020 16:05:11] WARNING [django.request:228] Not Found: /static/js/popper.min.js.map
[23/Mar/2020 16:05:11] WARNING [django.server:154] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 77
[23/Mar/2020 16:05:11] WARNING [django.server:154] "GET /static/js/popper.min.js.map HTTP/1.1" 404 77
[23/Mar/2020 16:05:22] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 16:05:23] WARNING [django.request:228] Not Found: /static/scss/_reboot.scss
[23/Mar/2020 16:05:23] WARNING [django.server:154] "GET /static/scss/_reboot.scss HTTP/1.1" 404 77
[23/Mar/2020 16:05:23] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 16:05:23] WARNING [django.request:228] Not Found: /static/js/popper.min.js.map
[23/Mar/2020 16:05:24] WARNING [django.request:228] Not Found: /static/js/bootstrap.min.js.map
[23/Mar/2020 16:05:24] WARNING [django.server:154] "GET /static/js/popper.min.js.map HTTP/1.1" 404 77
[23/Mar/2020 16:05:24] WARNING [django.server:154] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 77
[23/Mar/2020 16:05:57] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 16:05:57] WARNING [django.request:228] Not Found: /static/scss/_reboot.scss
[23/Mar/2020 16:05:57] WARNING [django.server:154] "GET /static/scss/_reboot.scss HTTP/1.1" 404 77
[23/Mar/2020 16:05:58] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 16:05:58] WARNING [django.request:228] Not Found: /static/js/popper.min.js.map
[23/Mar/2020 16:05:58] WARNING [django.request:228] Not Found: /static/js/bootstrap.min.js.map
[23/Mar/2020 16:05:58] WARNING [django.server:154] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 77
[23/Mar/2020 16:05:58] WARNING [django.server:154] "GET /static/js/popper.min.js.map HTTP/1.1" 404 77
[23/Mar/2020 16:06:22] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 16:06:22] WARNING [django.request:228] Not Found: /static/scss/_reboot.scss
[23/Mar/2020 16:06:22] WARNING [django.server:154] "GET /static/scss/_reboot.scss HTTP/1.1" 404 77
[23/Mar/2020 16:06:22] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 13871
[23/Mar/2020 16:06:23] WARNING [django.request:228] Not Found: /static/js/popper.min.js.map
[23/Mar/2020 16:06:23] WARNING [django.request:228] Not Found: /static/js/bootstrap.min.js.map
[23/Mar/2020 16:06:23] WARNING [django.server:154] "GET /static/js/popper.min.js.map HTTP/1.1" 404 77
[23/Mar/2020 16:06:23] WARNING [django.server:154] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 77
[23/Mar/2020 16:06:37] DEBUG [django.db.backends:111] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[23/Mar/2020 16:06:37] DEBUG [django.db.backends:111] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[23/Mar/2020 16:06:38] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 6059
[23/Mar/2020 16:06:38] WARNING [django.server:154] "GET /static/js/popper.min.js.map HTTP/1.1" 404 1785
[23/Mar/2020 16:06:38] WARNING [django.server:154] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1794
[23/Mar/2020 16:06:38] WARNING [django.server:154] "GET /static/scss/_reboot.scss HTTP/1.1" 404 1776
[23/Mar/2020 16:06:38] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 6059
[23/Mar/2020 16:06:47] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10005
[23/Mar/2020 16:06:47] WARNING [django.server:154] "GET /static/scss/_reboot.scss HTTP/1.1" 404 1776
[23/Mar/2020 16:06:47] WARNING [django.server:154] "GET /static/js/popper.min.js.map HTTP/1.1" 404 1785
[23/Mar/2020 16:06:48] WARNING [django.server:154] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1794
[23/Mar/2020 16:06:48] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10005
[23/Mar/2020 16:07:05] DEBUG [django.template:872] Exception while resolving variable 'name' in template 'Diabetes/Report.html'.
Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x0000022263F71598>>, 'request': <WSGIRequest: POST '/diabriskpred/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x0000022276385AE8>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000022276440160>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00000222763B69B0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'cholesterol': '15.3', 'hemoglobin': '34.2'}, {'block': <Block Node: content. Contents: [<TextNode: '\n<!DOCTYPE html>\n<html la'>, <django.templatetags.static.StaticNode object at 0x0000022276442518>, <TextNode: '" rel="stylesheet" />\n   '>, <Variable Node: name>, <TextNode: '\n                        '>, <Variable Node: age>, <TextNode: '\n                        '>, <Variable Node: gender>, <TextNode: '\n                        '>, <Variable Node: height>, <TextNode: '\n                        '>, <Variable Node: weight>, <TextNode: '\n                        '>, <Variable Node: hemoglobin>, <TextNode: '\n                        '>, <TextNode: '\n        <div class="prog'>, <TextNode: '\n                        '>, <TextNode: '\n                        '>, <Variable Node: bmi_calc>, <TextNode: '\n                        '>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n\n                       '>, <TextNode: '\n                        '>, <Variable Node: cholesterol>, <TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x0000022276440400>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x0000022276440320>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x00000222764402B0>, <TextNode: '" type="text/javascript">'>]>}]
[23/Mar/2020 16:07:05] DEBUG [django.template:872] Exception while resolving variable 'age' in template 'Diabetes/Report.html'.
Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'age'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'age'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'age'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [age] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x0000022263F71598>>, 'request': <WSGIRequest: POST '/diabriskpred/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x0000022276385AE8>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000022276440160>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00000222763B69B0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'cholesterol': '15.3', 'hemoglobin': '34.2'}, {'block': <Block Node: content. Contents: [<TextNode: '\n<!DOCTYPE html>\n<html la'>, <django.templatetags.static.StaticNode object at 0x0000022276442518>, <TextNode: '" rel="stylesheet" />\n   '>, <Variable Node: name>, <TextNode: '\n                        '>, <Variable Node: age>, <TextNode: '\n                        '>, <Variable Node: gender>, <TextNode: '\n                        '>, <Variable Node: height>, <TextNode: '\n                        '>, <Variable Node: weight>, <TextNode: '\n                        '>, <Variable Node: hemoglobin>, <TextNode: '\n                        '>, <TextNode: '\n        <div class="prog'>, <TextNode: '\n                        '>, <TextNode: '\n                        '>, <Variable Node: bmi_calc>, <TextNode: '\n                        '>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n\n                       '>, <TextNode: '\n                        '>, <Variable Node: cholesterol>, <TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x0000022276440400>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x0000022276440320>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x00000222764402B0>, <TextNode: '" type="text/javascript">'>]>}]
[23/Mar/2020 16:07:05] DEBUG [django.template:872] Exception while resolving variable 'gender' in template 'Diabetes/Report.html'.
Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'gender'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'gender'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'gender'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [gender] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x0000022263F71598>>, 'request': <WSGIRequest: POST '/diabriskpred/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x0000022276385AE8>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000022276440160>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00000222763B69B0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'cholesterol': '15.3', 'hemoglobin': '34.2'}, {'block': <Block Node: content. Contents: [<TextNode: '\n<!DOCTYPE html>\n<html la'>, <django.templatetags.static.StaticNode object at 0x0000022276442518>, <TextNode: '" rel="stylesheet" />\n   '>, <Variable Node: name>, <TextNode: '\n                        '>, <Variable Node: age>, <TextNode: '\n                        '>, <Variable Node: gender>, <TextNode: '\n                        '>, <Variable Node: height>, <TextNode: '\n                        '>, <Variable Node: weight>, <TextNode: '\n                        '>, <Variable Node: hemoglobin>, <TextNode: '\n                        '>, <TextNode: '\n        <div class="prog'>, <TextNode: '\n                        '>, <TextNode: '\n                        '>, <Variable Node: bmi_calc>, <TextNode: '\n                        '>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n\n                       '>, <TextNode: '\n                        '>, <Variable Node: cholesterol>, <TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x0000022276440400>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x0000022276440320>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x00000222764402B0>, <TextNode: '" type="text/javascript">'>]>}]
[23/Mar/2020 16:07:05] DEBUG [django.template:872] Exception while resolving variable 'height' in template 'Diabetes/Report.html'.
Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'height'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'height'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'height'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [height] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x0000022263F71598>>, 'request': <WSGIRequest: POST '/diabriskpred/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x0000022276385AE8>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000022276440160>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00000222763B69B0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'cholesterol': '15.3', 'hemoglobin': '34.2'}, {'block': <Block Node: content. Contents: [<TextNode: '\n<!DOCTYPE html>\n<html la'>, <django.templatetags.static.StaticNode object at 0x0000022276442518>, <TextNode: '" rel="stylesheet" />\n   '>, <Variable Node: name>, <TextNode: '\n                        '>, <Variable Node: age>, <TextNode: '\n                        '>, <Variable Node: gender>, <TextNode: '\n                        '>, <Variable Node: height>, <TextNode: '\n                        '>, <Variable Node: weight>, <TextNode: '\n                        '>, <Variable Node: hemoglobin>, <TextNode: '\n                        '>, <TextNode: '\n        <div class="prog'>, <TextNode: '\n                        '>, <TextNode: '\n                        '>, <Variable Node: bmi_calc>, <TextNode: '\n                        '>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n\n                       '>, <TextNode: '\n                        '>, <Variable Node: cholesterol>, <TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x0000022276440400>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x0000022276440320>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x00000222764402B0>, <TextNode: '" type="text/javascript">'>]>}]
[23/Mar/2020 16:07:05] DEBUG [django.template:872] Exception while resolving variable 'weight' in template 'Diabetes/Report.html'.
Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'weight'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'weight'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'weight'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [weight] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x0000022263F71598>>, 'request': <WSGIRequest: POST '/diabriskpred/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x0000022276385AE8>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000022276440160>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00000222763B69B0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'cholesterol': '15.3', 'hemoglobin': '34.2'}, {'block': <Block Node: content. Contents: [<TextNode: '\n<!DOCTYPE html>\n<html la'>, <django.templatetags.static.StaticNode object at 0x0000022276442518>, <TextNode: '" rel="stylesheet" />\n   '>, <Variable Node: name>, <TextNode: '\n                        '>, <Variable Node: age>, <TextNode: '\n                        '>, <Variable Node: gender>, <TextNode: '\n                        '>, <Variable Node: height>, <TextNode: '\n                        '>, <Variable Node: weight>, <TextNode: '\n                        '>, <Variable Node: hemoglobin>, <TextNode: '\n                        '>, <TextNode: '\n        <div class="prog'>, <TextNode: '\n                        '>, <TextNode: '\n                        '>, <Variable Node: bmi_calc>, <TextNode: '\n                        '>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n\n                       '>, <TextNode: '\n                        '>, <Variable Node: cholesterol>, <TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x0000022276440400>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x0000022276440320>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x00000222764402B0>, <TextNode: '" type="text/javascript">'>]>}]
[23/Mar/2020 16:07:05] DEBUG [django.template:872] Exception while resolving variable 'bmi_calc' in template 'Diabetes/Report.html'.
Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'bmi_calc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'bmi_calc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'bmi_calc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [bmi_calc] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x0000022263F71598>>, 'request': <WSGIRequest: POST '/diabriskpred/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x0000022276385AE8>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000022276440160>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00000222763B69B0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'cholesterol': '15.3', 'hemoglobin': '34.2'}, {'block': <Block Node: content. Contents: [<TextNode: '\n<!DOCTYPE html>\n<html la'>, <django.templatetags.static.StaticNode object at 0x0000022276442518>, <TextNode: '" rel="stylesheet" />\n   '>, <Variable Node: name>, <TextNode: '\n                        '>, <Variable Node: age>, <TextNode: '\n                        '>, <Variable Node: gender>, <TextNode: '\n                        '>, <Variable Node: height>, <TextNode: '\n                        '>, <Variable Node: weight>, <TextNode: '\n                        '>, <Variable Node: hemoglobin>, <TextNode: '\n                        '>, <TextNode: '\n        <div class="prog'>, <TextNode: '\n                        '>, <TextNode: '\n                        '>, <Variable Node: bmi_calc>, <TextNode: '\n                        '>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n'>, <TextNode: '\n\n                       '>, <TextNode: '\n                        '>, <Variable Node: cholesterol>, <TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x0000022276440400>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x0000022276440320>, <TextNode: '" type="text/javascript">'>, <django.templatetags.static.StaticNode object at 0x00000222764402B0>, <TextNode: '" type="text/javascript">'>]>}]
[23/Mar/2020 16:07:05] INFO [django.server:154] "POST /diabriskpred/ HTTP/1.1" 200 27125
[23/Mar/2020 16:07:06] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10005
[23/Mar/2020 16:07:10] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10005
[23/Mar/2020 16:07:56] INFO [django.server:154] "GET / HTTP/1.1" 200 11446
[23/Mar/2020 16:07:56] INFO [django.server:154] "GET / HTTP/1.1" 200 11446
[23/Mar/2020 16:18:12] INFO [django.server:154] "GET / HTTP/1.1" 200 11445
[23/Mar/2020 16:18:12] INFO [django.server:154] "GET /static/img/bakimg2.jpg HTTP/1.1" 200 3911317
[23/Mar/2020 16:18:15] INFO [django.server:154] "GET / HTTP/1.1" 200 11445
[23/Mar/2020 16:24:29] INFO [django.server:154] "GET / HTTP/1.1" 200 11457
[23/Mar/2020 16:24:29] INFO [django.server:154] "GET /static/img/bakimg2.jpg HTTP/1.1" 304 0
[23/Mar/2020 16:24:29] INFO [django.server:154] "GET / HTTP/1.1" 200 11457
[23/Mar/2020 16:24:56] INFO [django.server:154] "GET / HTTP/1.1" 200 11445
[23/Mar/2020 16:24:57] INFO [django.server:154] "GET / HTTP/1.1" 200 11445
[23/Mar/2020 16:25:19] INFO [django.server:154] "GET / HTTP/1.1" 200 11487
[23/Mar/2020 16:25:19] INFO [django.server:154] "GET / HTTP/1.1" 200 11487
[23/Mar/2020 16:25:29] INFO [django.server:154] "GET / HTTP/1.1" 200 11487
[23/Mar/2020 16:25:29] INFO [django.server:154] "GET / HTTP/1.1" 200 11487
[23/Mar/2020 16:25:46] INFO [django.server:154] "GET / HTTP/1.1" 200 11487
[23/Mar/2020 16:25:47] INFO [django.server:154] "GET /static/img/bakimg2.jpg HTTP/1.1" 304 0
[23/Mar/2020 16:25:47] INFO [django.server:154] "GET / HTTP/1.1" 200 11487
[23/Mar/2020 16:26:01] INFO [django.server:154] "GET / HTTP/1.1" 200 11499
[23/Mar/2020 16:26:01] INFO [django.server:154] "GET / HTTP/1.1" 200 11499
[23/Mar/2020 16:26:19] WARNING [django.server:154] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1794
[23/Mar/2020 16:26:19] WARNING [django.server:154] "GET /static/js/popper.min.js.map HTTP/1.1" 404 1785
[23/Mar/2020 16:26:32] INFO [django.server:154] "GET / HTTP/1.1" 200 11501
[23/Mar/2020 16:26:32] WARNING [django.server:154] "GET /static/js/popper.min.js.map HTTP/1.1" 404 1785
[23/Mar/2020 16:26:32] WARNING [django.server:154] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1794
[23/Mar/2020 16:26:34] INFO [django.server:154] "GET / HTTP/1.1" 200 11501
[23/Mar/2020 16:26:42] INFO [django.server:154] "GET / HTTP/1.1" 200 11498
[23/Mar/2020 16:26:43] INFO [django.server:154] "GET / HTTP/1.1" 200 11498
[23/Mar/2020 16:26:53] INFO [django.server:154] "GET / HTTP/1.1" 200 11499
[23/Mar/2020 16:26:53] INFO [django.server:154] "GET / HTTP/1.1" 200 11499
[23/Mar/2020 16:27:12] INFO [django.server:154] "GET / HTTP/1.1" 200 11520
[23/Mar/2020 16:27:12] INFO [django.server:154] "GET /static/img/bakimg2.jpg HTTP/1.1" 304 0
[23/Mar/2020 16:27:12] INFO [django.server:154] "GET / HTTP/1.1" 200 11520
[23/Mar/2020 16:27:41] INFO [django.server:154] "GET / HTTP/1.1" 200 11508
[23/Mar/2020 16:27:42] INFO [django.server:154] "GET / HTTP/1.1" 200 11508
[23/Mar/2020 16:27:53] INFO [django.server:154] "GET / HTTP/1.1" 200 11459
[23/Mar/2020 16:27:53] INFO [django.server:154] "GET / HTTP/1.1" 200 11459
[23/Mar/2020 16:28:10] INFO [django.server:154] "GET / HTTP/1.1" 200 11520
[23/Mar/2020 16:28:10] DEBUG [django.template:872] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\core\handlers\base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\urls\resolvers.py", line 520, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'medapp.urls' from 'C:\\Users\\AKUL\\Desktop\\mediport\\medapp\\urls.py'> (None:None) ''>, <URLPattern '' [name='home']>], [<URLResolver <module 'medapp.urls' from 'C:\\Users\\AKUL\\Desktop\\mediport\\medapp\\urls.py'> (None:None) ''>, <URLPattern 'contact/' [name='contact']>], [<URLResolver <module 'medapp.urls' from 'C:\\Users\\AKUL\\Desktop\\mediport\\medapp\\urls.py'> (None:None) ''>, <URLPattern 'diabriskpred/' [name='diabriskpred']>], [<URLResolver <module 'medapp.urls' from 'C:\\Users\\AKUL\\Desktop\\mediport\\medapp\\urls.py'> (None:None) ''>, <URLPattern 'bloodprofile/' [name='bloodprofile']>], [<URLResolver <module 'medapp.urls' from 'C:\\Users\\AKUL\\Desktop\\mediport\\medapp\\urls.py'> (None:None) ''>, <URLPattern 'diabetes_result/' [name='diabetes_report']>], [<URLResolver <module 'medapp.urls' from 'C:\\Users\\AKUL\\Desktop\\mediport\\medapp\\urls.py'> (None:None) ''>, <URLPattern 'blood_result/' [name='blood_report']>], [<URLResolver <module 'medapp.urls' from 'C:\\Users\\AKUL\\Desktop\\mediport\\medapp\\urls.py'> (None:None) ''>, <URLPattern '^static\/(?P<path>.*)$'>], [<URLPattern '^media\/(?P<path>.*)$'>]], 'path': "url('/static/img/bakimg2.jpg');"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKUL\Desktop\mediport\virenv\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
[23/Mar/2020 16:28:10] WARNING [django.request:228] Not Found: /url('/static/img/bakimg2.jpg');
[23/Mar/2020 16:28:10] WARNING [django.server:154] "GET /url('/static/img/bakimg2.jpg'); HTTP/1.1" 404 3423
[23/Mar/2020 16:28:11] INFO [django.server:154] "GET / HTTP/1.1" 200 11520
[23/Mar/2020 16:28:24] INFO [django.server:154] "GET / HTTP/1.1" 200 11513
[23/Mar/2020 16:28:24] WARNING [django.server:154] "GET /static/img/bakimg2.jpg; HTTP/1.1" 404 1775
[23/Mar/2020 16:28:24] WARNING [django.server:154] "GET /static/img/bakimg2.jpg; HTTP/1.1" 404 1775
[23/Mar/2020 16:28:24] INFO [django.server:154] "GET / HTTP/1.1" 200 11513
[23/Mar/2020 16:30:05] INFO [django.server:154] "GET / HTTP/1.1" 200 11562
[23/Mar/2020 16:30:05] INFO [django.server:154] "GET /static/img/bakimg2.jpg HTTP/1.1" 304 0
[23/Mar/2020 16:30:06] INFO [django.server:154] "GET / HTTP/1.1" 200 11562
[23/Mar/2020 16:30:18] INFO [django.server:154] "GET / HTTP/1.1" 200 11561
[23/Mar/2020 16:30:19] INFO [django.server:154] "GET / HTTP/1.1" 200 11561
[23/Mar/2020 16:31:04] INFO [django.server:154] "GET / HTTP/1.1" 200 11502
[23/Mar/2020 16:31:04] INFO [django.server:154] "GET / HTTP/1.1" 200 11502
[23/Mar/2020 16:31:12] INFO [django.server:154] "GET / HTTP/1.1" 200 11508
[23/Mar/2020 16:31:12] INFO [django.server:154] "GET / HTTP/1.1" 200 11508
[23/Mar/2020 16:31:24] INFO [django.server:154] "GET / HTTP/1.1" 200 11724
[23/Mar/2020 16:31:26] INFO [django.server:154] "GET / HTTP/1.1" 200 11724
[23/Mar/2020 16:31:40] INFO [django.server:154] "GET / HTTP/1.1" 200 11709
[23/Mar/2020 16:31:41] INFO [django.server:154] "GET / HTTP/1.1" 200 11709
[23/Mar/2020 16:31:53] INFO [django.server:154] "GET / HTTP/1.1" 200 11709
[23/Mar/2020 16:31:53] INFO [django.server:154] "GET /static/img/bakimg2.jpg HTTP/1.1" 304 0
[23/Mar/2020 16:31:53] INFO [django.server:154] "GET / HTTP/1.1" 200 11709
[23/Mar/2020 16:32:02] INFO [django.server:154] "GET / HTTP/1.1" 200 11709
[23/Mar/2020 16:32:02] INFO [django.server:154] "GET / HTTP/1.1" 200 11709
[23/Mar/2020 16:32:09] INFO [django.server:154] "GET / HTTP/1.1" 200 11709
[23/Mar/2020 16:32:09] INFO [django.server:154] "GET / HTTP/1.1" 200 11709
[23/Mar/2020 16:32:15] INFO [django.server:154] "GET / HTTP/1.1" 200 11709
[23/Mar/2020 16:32:16] INFO [django.server:154] "GET / HTTP/1.1" 200 11709
[23/Mar/2020 16:32:23] INFO [django.server:154] "GET / HTTP/1.1" 200 11709
[23/Mar/2020 16:32:23] INFO [django.server:154] "GET / HTTP/1.1" 200 11709
[23/Mar/2020 16:32:45] INFO [django.server:154] "GET / HTTP/1.1" 200 11533
[23/Mar/2020 16:32:45] INFO [django.server:154] "GET / HTTP/1.1" 200 11533
[23/Mar/2020 16:32:53] INFO [django.server:154] "GET / HTTP/1.1" 200 11533
[23/Mar/2020 16:32:53] INFO [django.server:154] "GET /static/img/bakimg1.jpg HTTP/1.1" 200 643117
[23/Mar/2020 16:32:53] INFO [django.server:154] "GET / HTTP/1.1" 200 11533
[23/Mar/2020 16:33:12] INFO [django.server:154] "GET / HTTP/1.1" 200 11501
[23/Mar/2020 16:33:12] INFO [django.server:154] "GET / HTTP/1.1" 200 11501
[23/Mar/2020 16:33:48] INFO [django.server:154] "GET / HTTP/1.1" 200 11807
[23/Mar/2020 16:33:49] INFO [django.server:154] "GET /static/img/bakimg2.jpg HTTP/1.1" 304 0
[23/Mar/2020 16:33:49] INFO [django.server:154] "GET / HTTP/1.1" 200 11807
[23/Mar/2020 17:24:22] INFO [django.server:154] "GET / HTTP/1.1" 200 11807
[23/Mar/2020 17:24:22] INFO [django.server:154] "GET /static/img/bakimg2.jpg HTTP/1.1" 304 0
[23/Mar/2020 17:24:22] INFO [django.server:154] "GET /static/img/bakimg1.jpg HTTP/1.1" 304 0
[23/Mar/2020 17:24:22] INFO [django.server:154] "GET / HTTP/1.1" 200 11807
[23/Mar/2020 17:29:25] INFO [django.server:154] "GET / HTTP/1.1" 200 11797
[23/Mar/2020 17:29:25] INFO [django.server:154] "GET / HTTP/1.1" 200 11797
[23/Mar/2020 17:29:40] INFO [django.server:154] "GET / HTTP/1.1" 200 11749
[23/Mar/2020 17:29:40] INFO [django.server:154] "GET / HTTP/1.1" 200 11749
[23/Mar/2020 17:29:53] INFO [django.server:154] "GET / HTTP/1.1" 200 11799
[23/Mar/2020 17:29:53] INFO [django.server:154] "GET / HTTP/1.1" 200 11799
[23/Mar/2020 17:30:25] INFO [django.server:154] "GET / HTTP/1.1" 200 11835
[23/Mar/2020 17:30:25] INFO [django.server:154] "GET / HTTP/1.1" 200 11835
[23/Mar/2020 17:30:59] INFO [django.server:154] "GET / HTTP/1.1" 200 11875
[23/Mar/2020 17:30:59] INFO [django.server:154] "GET / HTTP/1.1" 200 11875
[23/Mar/2020 17:31:20] INFO [django.server:154] "GET / HTTP/1.1" 200 11906
[23/Mar/2020 17:31:20] INFO [django.server:154] "GET / HTTP/1.1" 200 11906
[23/Mar/2020 17:31:32] INFO [django.server:154] "GET / HTTP/1.1" 200 11908
[23/Mar/2020 17:31:32] INFO [django.server:154] "GET /static/img/bakimg1.jpg HTTP/1.1" 304 0
[23/Mar/2020 17:31:32] INFO [django.server:154] "GET /static/img/bakimg2.jpg HTTP/1.1" 304 0
[23/Mar/2020 17:31:32] INFO [django.server:154] "GET / HTTP/1.1" 200 11908
[23/Mar/2020 17:31:40] INFO [django.server:154] "GET / HTTP/1.1" 200 11906
[23/Mar/2020 17:31:40] INFO [django.server:154] "GET / HTTP/1.1" 200 11906
[23/Mar/2020 17:31:53] INFO [django.server:154] "GET / HTTP/1.1" 200 11937
[23/Mar/2020 17:31:53] INFO [django.server:154] "GET / HTTP/1.1" 200 11937
[23/Mar/2020 17:33:08] WARNING [django.server:154] "GET /static/js/popper.min.js.map HTTP/1.1" 404 1785
[23/Mar/2020 17:33:08] WARNING [django.server:154] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1794
[23/Mar/2020 17:34:32] WARNING [django.server:154] "GET /static/scss/_reboot.scss HTTP/1.1" 404 1776
[23/Mar/2020 17:36:12] INFO [django.server:154] "GET / HTTP/1.1" 200 11989
[23/Mar/2020 17:36:13] INFO [django.server:154] "GET / HTTP/1.1" 200 11989
[23/Mar/2020 17:36:27] INFO [django.server:154] "GET / HTTP/1.1" 200 12011
[23/Mar/2020 17:36:28] INFO [django.server:154] "GET / HTTP/1.1" 200 12011
[23/Mar/2020 17:36:41] INFO [django.server:154] "GET / HTTP/1.1" 200 12036
[23/Mar/2020 17:36:41] INFO [django.server:154] "GET / HTTP/1.1" 200 12036
[23/Mar/2020 17:36:52] INFO [django.server:154] "GET / HTTP/1.1" 200 12063
[23/Mar/2020 17:36:52] INFO [django.server:154] "GET / HTTP/1.1" 200 12063
[23/Mar/2020 17:38:12] INFO [django.server:154] "GET / HTTP/1.1" 200 12030
[23/Mar/2020 17:38:12] INFO [django.server:154] "GET / HTTP/1.1" 200 12030
[23/Mar/2020 17:38:25] INFO [django.server:154] "GET / HTTP/1.1" 200 12053
[23/Mar/2020 17:38:26] INFO [django.server:154] "GET / HTTP/1.1" 200 12053
[23/Mar/2020 17:39:15] INFO [django.server:154] "GET / HTTP/1.1" 200 13357
[23/Mar/2020 17:39:16] INFO [django.server:154] "GET / HTTP/1.1" 200 13357
[23/Mar/2020 17:40:07] INFO [django.server:154] "GET / HTTP/1.1" 200 13327
[23/Mar/2020 17:40:07] INFO [django.server:154] "GET /static/img/bakimg1.jpg HTTP/1.1" 304 0
[23/Mar/2020 17:40:07] INFO [django.server:154] "GET /static/img/bakimg2.jpg HTTP/1.1" 304 0
[23/Mar/2020 17:40:07] INFO [django.server:154] "GET / HTTP/1.1" 200 13327
[23/Mar/2020 17:40:23] INFO [django.server:154] "GET / HTTP/1.1" 200 13331
[23/Mar/2020 17:40:23] INFO [django.server:154] "GET / HTTP/1.1" 200 13331
[23/Mar/2020 17:40:37] INFO [django.server:154] "GET / HTTP/1.1" 200 13331
[23/Mar/2020 17:40:37] INFO [django.server:154] "GET / HTTP/1.1" 200 13331
[23/Mar/2020 17:40:56] INFO [django.server:154] "GET / HTTP/1.1" 200 13339
[23/Mar/2020 17:40:56] INFO [django.server:154] "GET / HTTP/1.1" 200 13339
[23/Mar/2020 17:41:06] INFO [django.server:154] "GET / HTTP/1.1" 200 13339
[23/Mar/2020 17:41:07] INFO [django.server:154] "GET / HTTP/1.1" 200 13339
[23/Mar/2020 17:41:39] INFO [django.server:154] "GET / HTTP/1.1" 200 13340
[23/Mar/2020 17:41:40] INFO [django.server:154] "GET / HTTP/1.1" 200 13340
[23/Mar/2020 17:42:02] INFO [django.server:154] "GET / HTTP/1.1" 200 13345
[23/Mar/2020 17:42:03] INFO [django.server:154] "GET / HTTP/1.1" 200 13345
[23/Mar/2020 17:42:19] INFO [django.server:154] "GET / HTTP/1.1" 200 13365
[23/Mar/2020 17:42:19] INFO [django.server:154] "GET / HTTP/1.1" 200 13365
[23/Mar/2020 17:42:32] INFO [django.server:154] "GET / HTTP/1.1" 200 13357
[23/Mar/2020 17:42:32] INFO [django.server:154] "GET / HTTP/1.1" 200 13357
[23/Mar/2020 17:44:03] INFO [django.server:154] "GET / HTTP/1.1" 200 13362
[23/Mar/2020 17:44:03] INFO [django.server:154] "GET / HTTP/1.1" 200 13362
[23/Mar/2020 17:44:34] WARNING [django.server:154] "GET /static/js/popper.min.js.map HTTP/1.1" 404 1785
[23/Mar/2020 17:44:34] WARNING [django.server:154] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1794
[23/Mar/2020 17:44:53] INFO [django.server:154] "GET / HTTP/1.1" 200 13367
[23/Mar/2020 17:44:54] WARNING [django.server:154] "GET /static/js/popper.min.js.map HTTP/1.1" 404 1785
[23/Mar/2020 17:44:54] WARNING [django.server:154] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1794
[23/Mar/2020 17:44:54] INFO [django.server:154] "GET / HTTP/1.1" 200 13367
[23/Mar/2020 17:45:10] INFO [django.server:154] "GET / HTTP/1.1" 200 13367
[23/Mar/2020 17:45:10] INFO [django.server:154] "GET / HTTP/1.1" 200 13367
[23/Mar/2020 17:45:26] INFO [django.server:154] "GET / HTTP/1.1" 200 13357
[23/Mar/2020 17:45:26] INFO [django.server:154] "GET / HTTP/1.1" 200 13357
[23/Mar/2020 17:46:39] INFO [django.server:154] "GET / HTTP/1.1" 200 13362
[23/Mar/2020 17:46:39] INFO [django.server:154] "GET / HTTP/1.1" 200 13362
[23/Mar/2020 17:46:55] INFO [django.server:154] "GET / HTTP/1.1" 200 13362
[23/Mar/2020 17:46:56] INFO [django.server:154] "GET / HTTP/1.1" 200 13362
[23/Mar/2020 17:47:32] INFO [django.server:154] "GET / HTTP/1.1" 200 13361
[23/Mar/2020 17:47:32] INFO [django.server:154] "GET / HTTP/1.1" 200 13361
[23/Mar/2020 17:47:53] INFO [django.server:154] "GET / HTTP/1.1" 200 13358
[23/Mar/2020 17:47:53] INFO [django.server:154] "GET / HTTP/1.1" 200 13358
[23/Mar/2020 17:48:43] INFO [django.server:154] "GET / HTTP/1.1" 200 11010
[23/Mar/2020 17:48:43] INFO [django.server:154] "GET / HTTP/1.1" 200 11010
[23/Mar/2020 17:49:24] INFO [django.server:154] "GET / HTTP/1.1" 200 13413
[23/Mar/2020 17:49:24] INFO [django.server:154] "GET /static/img/bakimg1.jpg HTTP/1.1" 304 0
[23/Mar/2020 17:49:24] INFO [django.server:154] "GET /static/img/bakimg2.jpg HTTP/1.1" 304 0
[23/Mar/2020 17:49:24] INFO [django.server:154] "GET / HTTP/1.1" 200 13413
[23/Mar/2020 17:52:51] INFO [django.server:154] "GET / HTTP/1.1" 200 13528
[23/Mar/2020 17:52:52] INFO [django.server:154] "GET / HTTP/1.1" 200 13528
[23/Mar/2020 17:52:58] INFO [django.server:154] "GET / HTTP/1.1" 200 13497
[23/Mar/2020 17:52:59] INFO [django.server:154] "GET / HTTP/1.1" 200 13497
[23/Mar/2020 17:56:07] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 17:56:10] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 17:58:22] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 17:58:27] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 17:58:47] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10005
[23/Mar/2020 17:58:47] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10005
[23/Mar/2020 17:58:51] INFO [django.server:154] "GET /contact/ HTTP/1.1" 200 8435
[23/Mar/2020 17:58:51] INFO [django.server:154] "GET /contact/ HTTP/1.1" 200 8435
[23/Mar/2020 17:58:53] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 17:58:54] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 17:59:56] WARNING [django.server:154] "GET /static/js/popper.min.js.map HTTP/1.1" 404 1785
[23/Mar/2020 17:59:56] WARNING [django.server:154] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1794
[23/Mar/2020 17:59:56] INFO [django.server:154] "GET /static/img/bakimg1.jpg HTTP/1.1" 304 0
[23/Mar/2020 17:59:56] INFO [django.server:154] "GET /static/img/bakimg2.jpg HTTP/1.1" 304 0
[23/Mar/2020 18:14:53] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 18:14:53] INFO [django.server:154] "GET /static/img/bakimg1.jpg HTTP/1.1" 304 0
[23/Mar/2020 18:14:53] INFO [django.server:154] "GET /static/img/bakimg2.jpg HTTP/1.1" 304 0
[23/Mar/2020 18:14:56] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 18:15:17] INFO [django.server:154] "GET /contact/ HTTP/1.1" 200 8435
[23/Mar/2020 18:15:17] INFO [django.server:154] "GET /contact/ HTTP/1.1" 200 8435
[23/Mar/2020 18:23:23] INFO [django.server:154] "GET /contact/ HTTP/1.1" 200 8388
[23/Mar/2020 18:23:23] INFO [django.server:154] "GET /contact/ HTTP/1.1" 200 8388
[23/Mar/2020 18:23:48] INFO [django.server:154] "GET /contact/ HTTP/1.1" 200 8308
[23/Mar/2020 18:23:48] INFO [django.server:154] "GET /contact/ HTTP/1.1" 200 8308
[23/Mar/2020 18:24:02] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 18:24:02] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 18:24:32] INFO [django.server:154] "GET /contact/ HTTP/1.1" 200 8308
[23/Mar/2020 18:24:32] INFO [django.server:154] "GET /contact/ HTTP/1.1" 200 8308
[23/Mar/2020 18:24:33] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 18:24:33] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 18:24:38] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10005
[23/Mar/2020 18:24:38] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10005
[23/Mar/2020 18:27:20] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10110
[23/Mar/2020 18:27:20] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10110
[23/Mar/2020 18:27:50] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10110
[23/Mar/2020 18:27:50] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10110
[23/Mar/2020 18:27:51] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10110
[23/Mar/2020 18:27:51] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10110
[23/Mar/2020 18:27:51] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10110
[23/Mar/2020 18:27:52] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10110
[23/Mar/2020 18:27:52] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10110
[23/Mar/2020 18:27:52] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10110
[23/Mar/2020 18:27:52] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10110
[23/Mar/2020 18:27:52] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10110
[23/Mar/2020 18:28:38] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10141
[23/Mar/2020 18:28:38] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10141
[23/Mar/2020 18:28:43] WARNING [django.server:154] "GET /static/js/popper.min.js.map HTTP/1.1" 404 1785
[23/Mar/2020 18:28:43] WARNING [django.server:154] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1794
[23/Mar/2020 18:29:18] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10114
[23/Mar/2020 18:29:19] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10114
[23/Mar/2020 18:29:24] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10111
[23/Mar/2020 18:29:24] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10111
[23/Mar/2020 18:29:58] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10131
[23/Mar/2020 18:29:59] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10131
[23/Mar/2020 18:30:38] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10131
[23/Mar/2020 18:30:38] INFO [django.server:154] "GET /diabriskpred/ HTTP/1.1" 200 10131
[23/Mar/2020 18:30:41] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 18:30:41] INFO [django.server:154] "GET /static/img/bakimg1.jpg HTTP/1.1" 304 0
[23/Mar/2020 18:30:41] INFO [django.server:154] "GET /static/img/bakimg2.jpg HTTP/1.1" 304 0
[23/Mar/2020 18:30:43] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 18:30:48] INFO [django.server:154] "GET /bloodprofile/ HTTP/1.1" 200 13326
[23/Mar/2020 18:30:48] INFO [django.server:154] "GET /bloodprofile/ HTTP/1.1" 200 13326
[23/Mar/2020 18:30:53] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 18:30:54] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 18:31:42] INFO [django.server:154] "GET /bloodprofile/ HTTP/1.1" 200 13326
[23/Mar/2020 18:31:42] INFO [django.server:154] "GET /bloodprofile/ HTTP/1.1" 200 13326
[23/Mar/2020 18:31:46] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
[23/Mar/2020 18:31:47] INFO [django.server:154] "GET / HTTP/1.1" 200 13527
